channels:
- conda-forge
dependencies:
- python=3.9.20
- pip<=24.3.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.0
  - numpy==1.23.5
  - pandas==2.0.3
  - psutil==6.1.0
  - scikit-learn==1.5.2
name: mlflow-env
